// <auto-generated />
using System;
using HotelManagementProjectfeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementProjectfeb.Migrations
{
    [DbContext(typeof(HotelManagementDataContext))]
    partial class HotelManagementDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Bill", b =>
                {
                    b.Property<Guid>("Bill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("prices")
                        .HasColumnType("float");

                    b.Property<int>("stay_dates")
                        .HasColumnType("int");

                    b.HasKey("Bill_id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Department", b =>
                {
                    b.Property<Guid>("Department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dapartment_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("manager_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Department_id");

                    b.HasIndex("manager_id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Guest", b =>
                {
                    b.Property<Guid>("Guest_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone_number")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("Receptionist_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("room_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guest_id");

                    b.HasIndex("Receptionist_Id");

                    b.HasIndex("room_id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Inventory", b =>
                {
                    b.Property<Guid>("Inventory_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Inventory_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Inventory_Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Manager", b =>
                {
                    b.Property<Guid>("manager_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Receptionist_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Room_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("department_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("manager_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.HasKey("manager_id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Receptionist", b =>
                {
                    b.Property<Guid>("Receptionist_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Department_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Guest_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Reservation_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("bill_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("manager_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("room_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.HasKey("Receptionist_Id");

                    b.HasIndex("Department_Id");

                    b.HasIndex("bill_id");

                    b.HasIndex("manager_id");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Reservation", b =>
                {
                    b.Property<Guid>("reservation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Check_in")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Check_out")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guest_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Receptionist_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("no_of_adults")
                        .HasColumnType("int");

                    b.Property<int>("no_of_children")
                        .HasColumnType("int");

                    b.Property<int>("no_of_nights")
                        .HasColumnType("int");

                    b.Property<Guid?>("room_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("reservation_id");

                    b.HasIndex("Guest_Id");

                    b.HasIndex("Receptionist_Id");

                    b.HasIndex("room_id");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Room", b =>
                {
                    b.Property<Guid>("room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Bill_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Check_out")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("check_in")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("guest_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("guest_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("manager_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("reservation_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("room_id");

                    b.HasIndex("Bill_id");

                    b.HasIndex("manager_id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ReceptionistRoom", b =>
                {
                    b.Property<Guid>("ReceptionistsReceptionist_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("room_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReceptionistsReceptionist_Id", "room_id");

                    b.HasIndex("room_id");

                    b.ToTable("ReceptionistRoom");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Department", b =>
                {
                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Manager", null)
                        .WithMany("Departments")
                        .HasForeignKey("manager_id");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Guest", b =>
                {
                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Receptionist", null)
                        .WithMany("Guest")
                        .HasForeignKey("Receptionist_Id");

                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Room", null)
                        .WithMany("Guests")
                        .HasForeignKey("room_id");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Receptionist", b =>
                {
                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("bill_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Manager", null)
                        .WithMany("Receptionist")
                        .HasForeignKey("manager_id");

                    b.Navigation("Bill");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Reservation", b =>
                {
                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("Guest_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Receptionist", null)
                        .WithMany("Reservations")
                        .HasForeignKey("Receptionist_Id");

                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Room", null)
                        .WithMany("Reservations")
                        .HasForeignKey("room_id");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Room", b =>
                {
                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Bill", null)
                        .WithMany("Rooms")
                        .HasForeignKey("Bill_id");

                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Manager", null)
                        .WithMany("Rooms")
                        .HasForeignKey("manager_id");
                });

            modelBuilder.Entity("ReceptionistRoom", b =>
                {
                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Receptionist", null)
                        .WithMany()
                        .HasForeignKey("ReceptionistsReceptionist_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementProjectfeb.Model.Domain.Room", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Bill", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Manager", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Receptionist");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Receptionist", b =>
                {
                    b.Navigation("Guest");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelManagementProjectfeb.Model.Domain.Room", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
